name: riverpod_infinite_scroll
description: Riverpod implementation of infinite_scroll_pagination, this package
  allows to use infinite_scroll_pagination with Riverpod abstracting away the
  complexity
version: 1.0.6
homepage: https://www.quantos.it
repository: https://github.com/ftognetto/riverpod_infinite_scroll

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  infinite_scroll_pagination: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter: null
