name: Docs

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  docs:
    runs-on: ubuntu-20.04
    name: Build Latest API Docs
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      #       ---- setup of systems

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.1'
          channel: 'stable'

      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2023-04-10
          override: true

      #       ---- Install extra tools

      - name: Install Dartdocs
        run: flutter pub global activate dartdoc

      #
      - name: Versions
        run: |
          echo "--- Rust"
          cargo -V
          echo "--- Flutter doctor"
          flutter doctor
          echo "--- dartdoct"
          flutter pub global run dartdoc --version

      #       ---- Actual build steps

      - name: Build Rust docs
        run: |
          cargo doc -p acter
          echo --- Moving docs
          mv target/doc/ docs/static/api/main/rust

      - name: Build Dart App
        run: flutter pub global run dartdoc --output ../docs/static/api/main/app/
        working-directory: app

      - name: Checking for bindings
        run: ls -ltas app/packages/rust_sdk/lib/

      - name: Build Dart SDK
        run: flutter pub global run dartdoc --output ../../../docs/static/api/main/dart-sdk/
        working-directory: app/packages/rust_sdk

      #       ---- Finalisation for github pages

      - name: build zola
        uses: shalzz/zola-deploy-action@v0.16.1-1
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: "gh-pages"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
