name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-20.04
    name: Build Latest API Docs
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

#       ---- setup of systems

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install supported toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

#                  ---- Install extra tools

      - name: Install Dartdocs
        run: flutter pub global activate dartdoc


#
      - name: Versions
        run: |
          echo "--- Rust"
          cargo -V
          echo "--- Flutter doctor"
          flutter doctor
          echo "--- dartdoct"
          flutter pub global run dartdoc --version

#       ---- Actual build steps

      - name: Build Rust docs
        run: |
          cargo doc -p effektio
          echo --- Moving docs
          mv target/doc/ docs/static/api/main/rust
          echo --- Copying bindings.dart
          cp native/effektio/bindings.dart effektio_flutter_sdk/lib/effektio_flutter_sdk_ffi.dart

      - name: Build Dart App
        run: flutter pub global run dartdoc --output ../docs/static/api/main/app/
        working-directory: app

      - name: "Checking for bindings"
        run: ls -ltas effektio_flutter_sdk/lib/

      - name: Build Dart SDK
        run: flutter pub global run dartdoc --output ../docs/static/api/main/dart-sdk/
        working-directory: effektio_flutter_sdk

#       ---- Finalisation for github pages

      - name: build zola
        uses: shalzz/zola-deploy-action@master
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          BUILD_DIR: docs
          PAGES_BRANCH: "gh-pages"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}